services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
  
  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: katzionDB
    ports:
    - 3306:3306
  