services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    environment:
      - "GOOGLE_CLIENT_ID=1007985231541-g28os9ecnqbsbae8vukncr67jtb31tcu.apps.googleusercontent.com"
      - "GOOGLE_CLIENT_SECRET=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"
      - "GOOGLE_REDIRECT=http://localhost/login/google/callback"  
      - "DB_CONNECTION=mysql"
      - "DB_HOST=katzionassignment-mysql_db-1"
      - "DB_PORT=3306"
      - "DB_ROOT_PASSWORD=root"
      - "DB_DATABASE=katzionDB"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: katzionDB
    ports:
    - 3306:3306
  